server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: database-route
          uri: lb://DATABASE-SERVICE
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true