name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - run: mvn test

  checkStyle:
    runs-on: ubuntu-latest
    name: Check Code

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - run: mvn checkstyle:check

  pmd:
    runs-on: ubuntu-latest
    name: PMD Analysis

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - run: mvn pmd:check

  pitest:
    runs-on: ubuntu-latest
    name: Pitest Mutation Testing
    needs:
      - test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - run: mvn test-compile org.pitest:pitest-maven:mutationCoverage

  jmeter:
    runs-on: ubuntu-latest
    name: Run JMeter Tests
    needs:
      - test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - run: mvn verify

  build:
    runs-on: ubuntu-latest
    name: Build
    needs:
      - test
      - checkstyle
      - pmd
      - pitest
      - jmeter

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'
      - run: mvn package