name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java
        with:
          distribution: 'corretto'
          java.version: '20'
      - run: mvn test

  check:
    runs-on: ubuntu-latest
    name: Check Code

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java
        with:
          distribution: 'corretto'
          java.version: '20'
      - run: mvn checkstyle:check

  build:
    runs-on: ubuntu-latest
    name: Build
    needs:
      -test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java
        with:
          distribution: 'corretto'
          java.version: '20'
      - run: mvn package